### ISSUE TITLE
"couldn't find pcap build or installation directory"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dugsong/pypcap#39]
```
I have installed python-pyrex and libpcap-dev.
I have tried running "make" and "sudo python setup.py config".
I keep getting the following error while trying to install pypcap1.1:
"""
make
python setup.py config 
running config
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    ext_modules = [ pcap ])
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 67, in run
    cPickle.dump(self._pcap_config([ self.with_pcap ]),
  File "setup.py", line 63, in _pcap_config
    raise "couldn't find pcap build or installation directory"
TypeError: exceptions must be old-style classes or derived from BaseException, 
not str
make: *** [all] Error 1
"""

I am trying to install pypcap1.1 using python 2.7.2 and Ubuntu 11.10.

```

Original issue reported on code.google.com by `johnj...@gmail.com` on 17 May 2012 at 2:30

**Comment by jue-jiang** [comment]
In ubuntu 14.04, pypcap can be installed directly by sudo apt-get install python-pypcap.
https://www.howtoinstall.co/en/ubuntu/precise/python-pypcap
